const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaDeEventosNivel1_Event3_Act2,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{MovimentoEmGrid: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Senóide: 0},
	{Inimigo: 0},
	{fragmento: 0},
	{Sólido: 0},
	{parede: 0},
	{Teclado: 0},
	{Mouse: 0},
	{GamerOver: 0},
	{BotaoReniciar: 0},
	{coração: 0},
	{Nvidas: 0},
	{textoFragm: 0},
	{Nfragm: 0},
	{Áudio: 0},
	{botaoVerde: 0},
	{fundoInicio: 0},
	{CodigoPerdido: 0},
	{Start: 0},
	{fundoGameOver: 0},
	{sistemaCorrompido: 0},
	{botaoVermelho: 0},
	{reiniciar: 0},
	{fundoSIsteRestaurado: 0},
	{sistemaRestaurado: 0},
	{botaoSair: 0},
	{Vidas: 0},
	{Moedas: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	fragmento: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	GamerOver: class extends self.ISpriteFontInstance {},
	BotaoReniciar: class extends self.ISpriteFontInstance {},
	coração: class extends self.ISpriteInstance {},
	Nvidas: class extends self.ITextInstance {},
	textoFragm: class extends self.ISpriteInstance {},
	Nfragm: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	botaoVerde: class extends self.ISpriteInstance {},
	fundoInicio: class extends self.ISpriteInstance {},
	CodigoPerdido: class extends self.ISpriteInstance {},
	Start: class extends self.ITextInstance {},
	fundoGameOver: class extends self.ISpriteInstance {},
	sistemaCorrompido: class extends self.ISpriteInstance {},
	botaoVermelho: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ITextInstance {},
	fundoSIsteRestaurado: class extends self.ISpriteInstance {},
	sistemaRestaurado: class extends self.ISpriteInstance {},
	botaoSair: class extends self.ISpriteInstance {}
}